-- ============================================================
-- seed_data.sql — بيانات أجواء الكاملة من ملف الإكسل الأصلي
-- 62 خدمة | 4 قطاعات | 12 إدارة | 4 منسقين
-- ============================================================
BEGIN;

-- 1. المنسقون (الأسماء واليوزرنيم المعتمدة)
INSERT INTO users (username, password_hash, full_name, role, is_active) VALUES ('amsabhani', '$2b$10$dBfGei.P0BBXalxX7fCfHOudIccRxTrwvbgHbEMrQqgz6wr23WQie', 'أنس سبهاني', 'coordinator', true) ON CONFLICT (username) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, is_active=EXCLUDED.is_active;
INSERT INTO users (username, password_hash, full_name, role, is_active) VALUES ('aaamalki', '$2b$10$dBfGei.P0BBXalxX7fCfHOudIccRxTrwvbgHbEMrQqgz6wr23WQie', 'عبدالله المالكي', 'coordinator', true) ON CONFLICT (username) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, is_active=EXCLUDED.is_active;
INSERT INTO users (username, password_hash, full_name, role, is_active) VALUES ('mhejazi', '$2b$10$dBfGei.P0BBXalxX7fCfHOudIccRxTrwvbgHbEMrQqgz6wr23WQie', 'ماجد حجازي', 'coordinator', true) ON CONFLICT (username) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, is_active=EXCLUDED.is_active;
INSERT INTO users (username, password_hash, full_name, role, is_active) VALUES ('alghamdimk', '$2b$10$dBfGei.P0BBXalxX7fCfHOudIccRxTrwvbgHbEMrQqgz6wr23WQie', 'محمد خلف الغامدي', 'coordinator', true) ON CONFLICT (username) DO UPDATE SET full_name=EXCLUDED.full_name, role=EXCLUDED.role, is_active=EXCLUDED.is_active;
-- حذف اليوزرنيمات القديمة إن وجدت
DELETE FROM users WHERE username IN ('anas.subhani', 'abdullah.almalki', 'majed.hijazi', 'mohammed.alghamdi') AND role='coordinator';

-- 2. القطاعات
INSERT INTO sectors (name, created_by) VALUES ('قطاع سلامة الطيران والاستدامة البيئية', (SELECT id FROM users WHERE role='admin' LIMIT 1)) ON CONFLICT (name) DO NOTHING;
INSERT INTO sectors (name, created_by) VALUES ('قطاع السياسات الاقتصادية والخدمات اللوجستية', (SELECT id FROM users WHERE role='admin' LIMIT 1)) ON CONFLICT (name) DO NOTHING;
INSERT INTO sectors (name, created_by) VALUES ('قطاع أمن الطيران', (SELECT id FROM users WHERE role='admin' LIMIT 1)) ON CONFLICT (name) DO NOTHING;
INSERT INTO sectors (name, created_by) VALUES ('النقل الجوي والتعاون الدولي', (SELECT id FROM users WHERE role='admin' LIMIT 1)) ON CONFLICT (name) DO NOTHING;

-- 3. الإدارات
INSERT INTO departments (name, sector_id) SELECT 'إدارة تراخيص منسوبي الطيران', s.id FROM sectors s WHERE s.name='قطاع سلامة الطيران والاستدامة البيئية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='إدارة تراخيص منسوبي الطيران' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لسلامة التشغيل الجوي', s.id FROM sectors s WHERE s.name='قطاع سلامة الطيران والاستدامة البيئية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لسلامة التشغيل الجوي' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لسلامة المطارات', s.id FROM sectors s WHERE s.name='قطاع سلامة الطيران والاستدامة البيئية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لسلامة المطارات' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لسلامة الملاحة الجوية', s.id FROM sectors s WHERE s.name='قطاع سلامة الطيران والاستدامة البيئية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لسلامة الملاحة الجوية' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لصلاحية الطيران', s.id FROM sectors s WHERE s.name='قطاع سلامة الطيران والاستدامة البيئية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لصلاحية الطيران' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الادارة العامة السلامة الملاحة', s.id FROM sectors s WHERE s.name='قطاع سلامة الطيران والاستدامة البيئية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الادارة العامة السلامة الملاحة' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة للتراخيص الاقتصادية', s.id FROM sectors s WHERE s.name='قطاع السياسات الاقتصادية والخدمات اللوجستية' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة للتراخيص الاقتصادية' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة للعمليات والتشريعات الأمنية', s.id FROM sectors s WHERE s.name='قطاع أمن الطيران' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة للعمليات والتشريعات الأمنية' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لتسهيلات', s.id FROM sectors s WHERE s.name='النقل الجوي والتعاون الدولي' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لتسهيلات' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لتعاون الدولي', s.id FROM sectors s WHERE s.name='النقل الجوي والتعاون الدولي' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لتعاون الدولي' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة لشؤون الحج والعمرة', s.id FROM sectors s WHERE s.name='النقل الجوي والتعاون الدولي' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة لشؤون الحج والعمرة' AND d.sector_id=s.id);
INSERT INTO departments (name, sector_id) SELECT 'الإدارة العامة للنقل الجوي', s.id FROM sectors s WHERE s.name='النقل الجوي والتعاون الدولي' AND NOT EXISTS (SELECT 1 FROM departments d WHERE d.name='الإدارة العامة للنقل الجوي' AND d.sector_id=s.id);

-- 4. الخدمات (62 خدمة)
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شطب تسجيل طائرة', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شطب تسجيل طائرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة تسجيل طائرة', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة تسجيل طائرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة نقل ملكية طائرة', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة نقل ملكية طائرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة حجز علامة تسجيل طائرة', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة حجز علامة تسجيل طائرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الحد الأدنى للفصل الرأسي المخفض – RVSM', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الحد الأدنى للفصل الرأسي المخفض – RVSM');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة استخدام قائمة الحد الأدنى من المعداتMEL', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة استخدام قائمة الحد الأدنى من المعداتMEL');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تمديد الفترة المجدولة لبرنامج الصيانة المعتمد', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تمديد الفترة المجدولة لبرنامج الصيانة المعتمد');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخصة مفتش مفوض', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخصة مفتش مفوض');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تصريح طيران خاص', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'عبدالحليم بخاري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تصريح طيران خاص');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخصة فني اصلاح طائرات', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'مصعب شار', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخصة فني اصلاح طائرات');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخصة مهندس اصلاح طائرات', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'مصعب شار', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخصة مهندس اصلاح طائرات');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة مصادقة على رخصة فني صيانة طائرات أجنبية', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'مصعب شار', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة مصادقة على رخصة فني صيانة طائرات أجنبية');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الموافقة على محطة الإصلاح لمرة واحدة', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'بدر المشخص', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الموافقة على محطة الإصلاح لمرة واحدة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة طراز طائرة', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لصلاحية الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'غسان قواص', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة طراز طائرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الموافقة على تمديد العمر الافتراضي للمعداتGSE', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة المطارات' LIMIT 1), (SELECT id FROM users WHERE full_name='ماجد حجازي' AND role='coordinator' LIMIT 1), 'معتز البار', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الموافقة على تمديد العمر الافتراضي للمعداتGSE');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخصة مراقب جوي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الادارة العامة السلامة الملاحة' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'بسام الغامدي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخصة مراقب جوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'شهادة تفويض مراقبة جوية في مركز تدريب معتمد', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الادارة العامة السلامة الملاحة' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'بسام الغامدي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='شهادة تفويض مراقبة جوية في مركز تدريب معتمد');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة جهاز تدريب محاكاة الطيران', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'كابتن طراد المالكي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة جهاز تدريب محاكاة الطيران');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تصريح طيار مؤقت', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'هاجد القحطاني', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تصريح طيار مؤقت');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة تفويض فاحص المرحل الجوي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'عمرو حلبي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة تفويض فاحص المرحل الجوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخصة مرحل جوي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'عمرو حلبي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخصة مرحل جوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة تفويض فاحص طاقم مقصورة الركاب', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'محمد سعادة', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة تفويض فاحص طاقم مقصورة الركاب');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة إلغاء او تأجيل فعالية طيران', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'منصور المعارك', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة إلغاء او تأجيل فعالية طيران');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تصريح فعالية طيران', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'منصور المعارك', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تصريح فعالية طيران');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة شهادة منظومة طيران ترفيهي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة التشغيل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'منصور المعارك', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة شهادة منظومة طيران ترفيهي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة قبول تقديم المساح الجوي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة الملاحة الجوية' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'خالد الحربي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة قبول تقديم المساح الجوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمه الموافقة على تعديل منتجات معلومات الطيران', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة الملاحة الجوية' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'خالد الحربي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمه الموافقة على تعديل منتجات معلومات الطيران');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الموافقة على تصميم إجراءات الطيران الآلي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة الملاحة الجوية' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'خالد الحربي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الموافقة على تصميم إجراءات الطيران الآلي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الموافقة على التغييرات في البيانات والأنظمة الرئيسية لمقدمي خدمات الملاحة الجوية', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة الملاحة الجوية' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'خالد الحربي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الموافقة على التغييرات في البيانات والأنظمة الرئيسية لمقدمي خدمات الملاحة الجوية');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الموافقة على تغييرالمجال الجوي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة الملاحة الجوية' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'خالد الحربي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الموافقة على تغييرالمجال الجوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تقييم العوائق', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لسلامة الملاحة الجوية' LIMIT 1), (SELECT id FROM users WHERE full_name='أنس سبهاني' AND role='coordinator' LIMIT 1), 'محمد خليفه', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تقييم العوائق');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص اقتصادي لناقل جوي وطني', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'زياد السليمان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص اقتصادي لناقل جوي وطني');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص اقتصادي لمزود خدمات دعم الطيران العام', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'زياد السليمان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص اقتصادي لمزود خدمات دعم الطيران العام');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص اقتصادي لوكيل تجاري لمقدم خدمات الطيران', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'زياد السليمان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص اقتصادي لوكيل تجاري لمقدم خدمات الطيران');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الترخيص الاقتصادي لناقل جوي اجنبي', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'زياد السليمان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الترخيص الاقتصادي لناقل جوي اجنبي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة موافقة اقتصادية لتشغيل عارض حج وعمرة', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'زياد السليمان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة موافقة اقتصادية لتشغيل عارض حج وعمرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخصة اقتصادية لتشغيل عارض حج و عمرة', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'زياد السليمان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخصة اقتصادية لتشغيل عارض حج و عمرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص اقتصادي لخدمات المناولة الأرضية', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'محمد البانمي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص اقتصادي لخدمات المناولة الأرضية');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص شاحن معتمد - موقع وشج', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'محمد البانمي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص شاحن معتمد - موقع وشج');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص شاحن الذاتي المعتمد-موقع وشج', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'محمد البانمي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص شاحن الذاتي المعتمد-موقع وشج');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة ترخيص اقتصادي لخدمات الشحن الجوي', (SELECT id FROM sectors WHERE name='قطاع السياسات الاقتصادية والخدمات اللوجستية' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للتراخيص الاقتصادية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'محمد البانمي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة ترخيص اقتصادي لخدمات الشحن الجوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة رخص القيادة', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), '', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة رخص القيادة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الموافقة على البرنامج الدليل الأمني', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'معن زامكة', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الموافقة على البرنامج الدليل الأمني');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الزيارات الميدانية -جزء أمن الطيران', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'معن زامكة', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الزيارات الميدانية -جزء أمن الطيران');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الغاء تصريح للمعدات والمركبات- موقع تصريح', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), '', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الغاء تصريح للمعدات والمركبات- موقع تصريح');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الغاء تصريح للافراد- موقع تصريح', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), '', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الغاء تصريح للافراد- موقع تصريح');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تصريح طلب تصريح امني للمعدات والمركبات- موقع تصريح', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), '', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تصريح طلب تصريح امني للمعدات والمركبات- موقع تصريح');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة طلب تصريح امني للافراد', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='محمد خلف الغامدي' AND role='coordinator' LIMIT 1), 'ندى الشهري', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة طلب تصريح امني للافراد');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة المسح الأمني', (SELECT id FROM sectors WHERE name='قطاع أمن الطيران' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للعمليات والتشريعات الأمنية' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'نادين السياط', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة المسح الأمني');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الاختبارات', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='إدارة تراخيص منسوبي الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'محمد الحربي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الاختبارات');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'رخصة مضيف جوي', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='إدارة تراخيص منسوبي الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'محمد بكر', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='رخصة مضيف جوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'الخدمات الداعمة للرخص', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='إدارة تراخيص منسوبي الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'محمد بكر', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='الخدمات الداعمة للرخص');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'رخصة طيار', (SELECT id FROM sectors WHERE name='قطاع سلامة الطيران والاستدامة البيئية' LIMIT 1), (SELECT id FROM departments WHERE name='إدارة تراخيص منسوبي الطيران' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'محمد بكر', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='رخصة طيار');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة إدارة الحج والعمرة', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لشؤون الحج والعمرة' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'عبدالله الخليفي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة إدارة الحج والعمرة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة الرمز المشترك', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للنقل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'محمد ازمرلي / سالم الصوفي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة الرمز المشترك');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'بطاقة عضو طاقم', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لتسهيلات' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'خالد هشلان', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='بطاقة عضو طاقم');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تعيين ناقل جوي وطني', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للنقل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'محمد ازمرلي / سالم الصوفي', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تعيين ناقل جوي وطني');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'الاتفاقيات الثنائية', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة لتعاون الدولي' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'عبير السحيباني', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='الاتفاقيات الثنائية');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تصريح رحلات طيران عام سنوي', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للنقل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'عبدالرحمن الجيزاني', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تصريح رحلات طيران عام سنوي');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة تصريح رحلة طيران عام مفردة', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للنقل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'عبدالرحمن الجيزاني', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة تصريح رحلة طيران عام مفردة');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'خدمة امر المهام الجوية العسكرية', (SELECT id FROM sectors WHERE name='النقل الجوي والتعاون الدولي' LIMIT 1), (SELECT id FROM departments WHERE name='الإدارة العامة للنقل الجوي' LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'عبدالرحمن الجيزاني', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='خدمة امر المهام الجوية العسكرية');
INSERT INTO services (name, sector_id, department_id, coordinator_id, service_owner, status) SELECT 'تسجيل الجهات', (SELECT id FROM sectors ORDER BY id LIMIT 1), (SELECT id FROM departments ORDER BY id LIMIT 1), (SELECT id FROM users WHERE full_name='عبدالله المالكي' AND role='coordinator' LIMIT 1), 'جميع القطاعات', 'مطلقة' WHERE NOT EXISTS (SELECT 1 FROM services WHERE name='تسجيل الجهات');

-- 5. ربط الخدمات بالمنسقين (مرجع: ملف الإكسل الأصلي — يعمل حتى لو الخدمات موجودة مسبقاً)

-- ماجد حجازي (15 خدمة)
UPDATE services SET coordinator_id = (SELECT id FROM users WHERE username='mhejazi' LIMIT 1)
WHERE name IN (
  'خدمة شطب تسجيل طائرة',
  'خدمة شهادة تسجيل طائرة',
  'خدمة نقل ملكية طائرة',
  'خدمة حجز علامة تسجيل طائرة',
  'خدمة الحد الأدنى للفصل الرأسي المخفض – RVSM',
  'خدمة استخدام قائمة الحد الأدنى من المعداتMEL',
  'خدمة تمديد الفترة المجدولة لبرنامج الصيانة المعتمد',
  'خدمة رخصة مفتش مفوض',
  'خدمة تصريح طيران خاص',
  'خدمة رخصة فني اصلاح طائرات',
  'خدمة رخصة مهندس اصلاح طائرات',
  'خدمة شهادة مصادقة على رخصة فني صيانة طائرات أجنبية',
  'خدمة الموافقة على محطة الإصلاح لمرة واحدة',
  'خدمة شهادة طراز طائرة',
  'خدمة الموافقة على تمديد العمر الافتراضي للمعداتGSE'
);

-- أنس سبهاني (16 خدمة)
UPDATE services SET coordinator_id = (SELECT id FROM users WHERE username='amsabhani' LIMIT 1)
WHERE name IN (
  'خدمة رخصة مراقب جوي',
  'شهادة تفويض مراقبة جوية في مركز تدريب معتمد',
  'خدمة شهادة جهاز تدريب  محاكاة الطيران',
  'خدمة  تصريح طيار مؤقت',
  'خدمة شهادة تفويض فاحص المرحل الجوي',
  'خدمة رخصة مرحل جوي',
  'خدمة شهادة تفويض فاحص طاقم مقصورة الركاب',
  'خدمة إلغاء او تأجيل فعالية طيران',
  'خدمة تصريح فعالية طيران',
  'خدمة شهادة منظومة طيران ترفيهي',
  'خدمة قبول تقديم المساح الجوي',
  'خدمه الموافقة على تعديل منتجات معلومات الطيران',
  'خدمة الموافقة على تصميم إجراءات الطيران الآلي',
  'خدمة الموافقة على التغييرات في البيانات والأنظمة الرئيسية لمقدمي خدمات الملاحة الجوية',
  'خدمة الموافقة على تغييرالمجال الجوي',
  'خدمة تقييم العوائق'
);

-- محمد خلف الغامدي (17 خدمة)
UPDATE services SET coordinator_id = (SELECT id FROM users WHERE username='alghamdimk' LIMIT 1)
WHERE name IN (
  'خدمة ترخيص اقتصادي لناقل جوي وطني',
  'خدمة ترخيص اقتصادي لمزود خدمات دعم الطيران العام',
  'خدمة ترخيص اقتصادي لوكيل تجاري لمقدم خدمات الطيران',
  'خدمة الترخيص الاقتصادي لناقل جوي اجنبي',
  'خدمة موافقة اقتصادية لتشغيل عارض حج وعمرة',
  'خدمة رخصة اقتصادية لتشغيل عارض حج و عمرة',
  'خدمة ترخيص اقتصادي لخدمات المناولة الأرضية',
  'خدمة ترخيص شاحن معتمد - موقع وشج',
  'خدمة ترخيص شاحن الذاتي المعتمد-موقع وشج',
  'خدمة ترخيص اقتصادي لخدمات الشحن الجوي',
  'خدمة رخص القيادة',
  'خدمة الموافقة على البرنامج الدليل الأمني',
  'خدمة الزيارات الميدانية -جزء أمن الطيران',
  'خدمة الغاء تصريح للمعدات والمركبات- موقع تصريح',
  'خدمة الغاء  تصريح للافراد- موقع تصريح',
  'خدمة تصريح طلب تصريح امني للمعدات والمركبات- موقع تصريح',
  'خدمة طلب تصريح امني للافراد'
);

-- عبدالله المالكي (14 خدمة)
UPDATE services SET coordinator_id = (SELECT id FROM users WHERE username='aaamalki' LIMIT 1)
WHERE name IN (
  'خدمة المسح الأمني',
  'خدمة  الاختبارات',
  'رخصة مضيف جوي',
  ' الخدمات الداعمة للرخص',
  'رخصة طيار',
  'خدمة  إدارة الحج والعمرة',
  'خدمة الرمز المشترك',
  'بطاقة عضو طاقم',
  'خدمة تعيين ناقل جوي وطني',
  'الاتفاقيات الثنائية',
  'خدمة تصريح رحلات طيران عام سنوي',
  'خدمة تصريح رحلة طيران عام مفردة',
  'خدمة امر المهام الجوية العسكرية',
  'تسجيل الجهات'
);

COMMIT;

-- تحقق
SELECT
  (SELECT COUNT(*) FROM users WHERE role='coordinator') AS منسقون,
  (SELECT COUNT(*) FROM sectors) AS قطاعات,
  (SELECT COUNT(*) FROM departments) AS ادارات,
  (SELECT COUNT(*) FROM services) AS خدمات,
  (SELECT COUNT(*) FROM services WHERE coordinator_id IS NULL) AS خدمات_بدون_منسق;